[project]
name = "shapeplotterfosfitter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "matplotlib==3.10.7",
    "numpy==2.3.5",
    "pylint>=4.0.3",
    "scipy==1.16.3",
    "scipy-stubs==1.16.3.0",
]
